IMAGE_REPO=zauberzeug/yolov5-trainer
TEST_LATEST_TAG=latest
CONTAINER_NAME="${TRAINER_NAME:-yolov5_trainer}"
DATA_VOLUME="$HOME/trainer_nodes_data"
HOST_PORT="${HOST_PORT:-7443}"
GPU=TRUE
IPC_HOST=TRUE
LINKLL_SITE_PACKAGES=/uv_venv/lib/python3.12/site-packages
NODE_TYPE=trainer
FORWARD_ENV="
  HOST USERNAME PASSWORD LOOP_SSL_CERT_PATH
  BATCH_SIZE ?UVICORN_RELOAD KEEP_OLD_TRAININGS
  NODE_TYPE YOLOV5_MODE RESTART_AFTER_TRAINING TRAINER_IDLE_TIMEOUT_SEC
  USE_BACKDOOR_CONTROLS
"
