name: docker

on:
  push:
    tags:
      - 'v*'

jobs:
  multi-arch:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - context: trainer/
            dockerfile: trainer/Dockerfile
            image: zauberzeug/yolov5-trainer
          - context: .
            dockerfile: detector_cpu/Dockerfile
            image: zauberzeug/yolov5-detector
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push
        run: |
          docker buildx build ${{ matrix.context }} \
            --platform linux/amd64,linux/arm64 \
            -f ${{ matrix.dockerfile }} \
            -t ${{ matrix.image }}:${GITHUB_REF_NAME#v} \
            --push

  detector-cloud:
    runs-on: [self-hosted, amd64]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push
        run: |
          docker build detector/ \
            -f detector/Dockerfile \
            --build-arg BASE_IMAGE=nvcr.io/nvidia/tensorrt:25.01-py3 \
            --build-arg INSTALL_OPENCV=true \
            -t zauberzeug/yolov5-detector:${GITHUB_REF_NAME#v}-cloud
          docker push zauberzeug/yolov5-detector:${GITHUB_REF_NAME#v}-cloud

  detector-jetson:
    runs-on: [self-hosted, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push
        run: |
          docker build detector/ \
            -f detector/Dockerfile \
            --build-arg BASE_IMAGE=dustynv/l4t-ml:r36.4.0 \
            --build-arg INSTALL_OPENCV=false \
            -t zauberzeug/yolov5-detector:${GITHUB_REF_NAME#v}-jetson
          docker push zauberzeug/yolov5-detector:${GITHUB_REF_NAME#v}-jetson
